import { z } from "zod";

import { hashCanonicalPayload } from "./canonical-json";
import { runtimeObservationV2Schema } from "./runtime-observation-v2";

export { canonicalizeJsonForHash, hashCanonicalPayload } from "./canonical-json";

export const RUNTIME_PROTOCOL_VERSION = "1.0" as const;
export const MAX_COMMAND_TTL_MS = 10 * 60 * 1000;
export const RUNTIME_CANONICALIZATION = "RFC8785" as const;
export const RUNTIME_OBSERVATION_V2_EVENT_TYPE = "runtime.observation_v2" as const;

const sha256 = z.string().regex(/^sha256:[a-f0-9]{64}$/);
const stateVersion = sha256;
const safeSequence = z.number().int().safe().positive();
const isoTimestamp = z.iso.datetime({ offset: true });
const softwareVersion = z.string().regex(/^[A-Za-z0-9][A-Za-z0-9._+-]{0,39}$/);
const opaqueAccountRef = z.string().regex(
  /^acct_[a-z0-9]{16,64}$/,
  "Use the opaque account reference generated by the local agent",
);
const opaqueStrategyRef = z.string().regex(
  /^strat_[a-z0-9]{16,64}$/,
  "Use the stable strategy reference generated by the Add-On",
);
const maskedIdentifier = z.string().regex(
  /^\*{4,16}[A-Za-z0-9]{2,8}$/,
  "Only an ASCII mask plus the final account characters may leave the local agent",
);
const identifierFingerprint = z.string().regex(
  /^hmac-sha256:[a-f0-9]{64}$/,
  "Expected a keyed account fingerprint",
);

const processInstallationRef = z.string().regex(/^install_[a-z0-9]{16,64}$/);
const processRef = z.string().regex(/^process_[a-f0-9]{64}$/);

const processObservationBase = {
  observedAt: isoTimestamp,
  installationRef: processInstallationRef,
};

/**
 * Process-only evidence is intentionally carried by the existing authenticated heartbeat.
 * It never includes an executable path, PID, or other raw local process identity.
 */
export const processObservationSchema = z.discriminatedUnion("state", [
  z.object({
    ...processObservationBase,
    state: z.literal("running"),
    processStateVersion: stateVersion,
    processRef,
    matchedProcessCount: z.literal(1),
    unavailableReason: z.null(),
  }).strict(),
  z.object({
    ...processObservationBase,
    state: z.literal("not_running"),
    processStateVersion: stateVersion,
    processRef: z.null(),
    matchedProcessCount: z.literal(0),
    unavailableReason: z.null(),
  }).strict(),
  z.object({
    ...processObservationBase,
    state: z.literal("ambiguous"),
    processStateVersion: stateVersion,
    processRef: z.null(),
    matchedProcessCount: z.number().int().min(1).max(100),
    unavailableReason: z.enum([
      "MULTIPLE_ACTIVE_PROCESSES",
      "TRANSITIONAL_PROCESS_STATE",
    ]),
  }).strict().superRefine((value, context) => {
    if (value.unavailableReason === "MULTIPLE_ACTIVE_PROCESSES" && value.matchedProcessCount < 2) {
      context.addIssue({
        code: "custom",
        message: "Multiple-active evidence requires at least two matched processes",
        path: ["matchedProcessCount"],
      });
    }
    if (value.unavailableReason === "TRANSITIONAL_PROCESS_STATE" && value.matchedProcessCount !== 1) {
      context.addIssue({
        code: "custom",
        message: "Transitional evidence requires exactly one matched process",
        path: ["matchedProcessCount"],
      });
    }
  }),
  z.object({
    ...processObservationBase,
    state: z.literal("unknown"),
    processStateVersion: z.null(),
    processRef: z.null(),
    matchedProcessCount: z.null(),
    unavailableReason: z.enum([
      "OBSERVATION_FAILED",
      "OBSERVATION_TIME_INVALID",
    ]),
  }).strict(),
]);
const canonicalAccountRefs = z.array(opaqueAccountRef).max(500).refine(
  (values) => values.every((value, index) => index === 0 || values[index - 1] < value),
  "Account references must be unique and sorted",
);

export const runtimeAccountObservationSchema = z.object({
  accountRef: opaqueAccountRef,
  maskedIdentifier,
  identifierFingerprint,
  displayLabel: z.string().regex(/^(?:Simulation|Evaluation|Live|Unknown) account [1-9][0-9]{0,2}$/),
  accountType: z.enum(["simulation", "evaluation", "live", "unknown"]),
  connectionKind: z.enum(["simulation", "brokerage", "market_data", "unknown"]),
  connectionStatus: z.enum(["connected", "connecting", "disconnected", "unknown"]),
}).strict();

export const runtimeStrategyObservationSchema = z.object({
  strategyRef: opaqueStrategyRef,
  accountRef: opaqueAccountRef,
  displayLabel: z.string().regex(/^Strategy [1-9][0-9]{0,4}$/),
  strategyType: z.string().regex(/^[A-Za-z][A-Za-z0-9_.-]{0,79}$/),
  instrumentCode: z.string().regex(/^[A-Z]{1,6}(?: [A-Z]{3}[0-9]{2})?$/),
  timeframeCode: z.string().regex(/^(?:[1-9][0-9]{0,2} (?:Second|Minute|Day)|Tick|Range)$/),
  enabled: z.boolean(),
  sync: z.boolean().nullable(),
  runtimeState: z.enum(["disabled", "waiting_sync", "running", "error", "unknown"]),
  stateCode: z.enum([
    "SYNCHRONIZED",
    "AWAITING_SYNC",
    "AWAITING_CONNECTION",
    "DISABLED_BY_CONFIGURATION",
    "ERROR_REPORTED",
    "UNKNOWN",
  ]).nullable(),
}).strict().superRefine((value, context) => {
  if (value.runtimeState === "running" && (!value.enabled || value.sync !== true)) {
    context.addIssue({ code: "custom", message: "Running requires enabled=true and sync=true" });
  }
  if (!value.enabled && value.runtimeState !== "disabled" && value.runtimeState !== "unknown") {
    context.addIssue({ code: "custom", message: "A disabled strategy cannot report an active runtime state" });
  }
});

export const runtimeSnapshotPayloadSchema = z.object({
  source: z.literal("ninjatrader_addon"),
  collectionMode: z.enum(["authoritative_read_only", "supervised_simulation"]),
  complete: z.literal(true),
  observedAt: isoTimestamp,
  addonVersion: softwareVersion,
  stateVersion,
  accounts: z.array(runtimeAccountObservationSchema).max(500),
  strategies: z.array(runtimeStrategyObservationSchema).max(10_000),
}).strict().superRefine((value, context) => {
  const accountRefs = new Set(value.accounts.map((account) => account.accountRef));
  if (accountRefs.size !== value.accounts.length) {
    context.addIssue({ code: "custom", message: "Snapshot contains duplicate account references", path: ["accounts"] });
  }
  if (!value.accounts.every((account, index) => index === 0 || value.accounts[index - 1].accountRef < account.accountRef)) {
    context.addIssue({ code: "custom", message: "Snapshot accounts must be sorted by account reference", path: ["accounts"] });
  }
  const accountFingerprints = new Set(value.accounts.map((account) => account.identifierFingerprint));
  if (accountFingerprints.size !== value.accounts.length) {
    context.addIssue({ code: "custom", message: "Snapshot contains duplicate account fingerprints", path: ["accounts"] });
  }
  const strategyRefs = new Set(value.strategies.map((strategy) => strategy.strategyRef));
  if (strategyRefs.size !== value.strategies.length) {
    context.addIssue({ code: "custom", message: "Snapshot contains duplicate strategy references", path: ["strategies"] });
  }
  if (!value.strategies.every((strategy, index) => index === 0 || value.strategies[index - 1].strategyRef < strategy.strategyRef)) {
    context.addIssue({ code: "custom", message: "Snapshot strategies must be sorted by strategy reference", path: ["strategies"] });
  }
  value.strategies.forEach((strategy, index) => {
    if (!accountRefs.has(strategy.accountRef)) {
      context.addIssue({
        code: "custom",
        message: "Strategy references an account absent from the complete snapshot",
        path: ["strategies", index, "accountRef"],
      });
    }
  });
  if (value.stateVersion !== runtimeStateVersion(value)) {
    context.addIssue({
      code: "custom",
      message: "State version does not match the canonical runtime state",
      path: ["stateVersion"],
    });
  }
});

export const agentHeartbeatPayloadSchema = z.object({
  source: z.literal("vps_companion_agent"),
  observedAt: isoTimestamp,
  agentVersion: softwareVersion,
  health: z.enum(["online", "degraded"]),
  addonConnected: z.boolean(),
  addonVersion: softwareVersion.nullable(),
  pendingEventCount: z.number().int().min(0).max(100_000),
  processObservation: processObservationSchema.optional(),
}).strict().superRefine((value, context) => {
  if (
    value.processObservation
    && Date.parse(value.processObservation.observedAt) > Date.parse(value.observedAt)
  ) {
    context.addIssue({
      code: "custom",
      message: "Process observation cannot postdate its enclosing heartbeat",
      path: ["processObservation", "observedAt"],
    });
  }
});

const eventEnvelopeShape = {
  protocolVersion: z.literal(RUNTIME_PROTOCOL_VERSION),
  eventId: z.uuid(),
  agentId: z.uuid(),
  sequence: safeSequence,
  correlationId: z.uuid().nullable(),
  causationId: z.uuid().nullable(),
  occurredAt: isoTimestamp,
  payloadHash: sha256,
  envelopeHash: sha256,
};

export const runtimeSnapshotEventSchema = z.object({
  ...eventEnvelopeShape,
  eventType: z.literal("runtime.snapshot"),
  payload: runtimeSnapshotPayloadSchema,
}).strict();

export const agentHeartbeatEventSchema = z.object({
  ...eventEnvelopeShape,
  eventType: z.literal("agent.heartbeat"),
  payload: agentHeartbeatPayloadSchema,
}).strict();

export const runtimeObservationV2EventSchema = z.object({
  ...eventEnvelopeShape,
  eventType: z.literal(RUNTIME_OBSERVATION_V2_EVENT_TYPE),
  payload: runtimeObservationV2Schema,
}).strict();

export const agentEventSchema = z.discriminatedUnion("eventType", [
  runtimeSnapshotEventSchema,
  agentHeartbeatEventSchema,
  runtimeObservationV2EventSchema,
]);

export const readOnlyCommandTypeSchema = z.enum([
  "DISCOVER_RUNTIME_STATE",
  "COLLECT_ACCOUNT_SNAPSHOT",
  "COLLECT_EXECUTIONS",
]);

const commandEnvelopeShape = {
  protocolVersion: z.literal(RUNTIME_PROTOCOL_VERSION),
  commandId: z.uuid(),
  correlationId: z.uuid(),
  agentId: z.uuid(),
  idempotencyKey: z.string().regex(/^[A-Za-z0-9:._-]{16,200}$/),
  issuedAt: isoTimestamp,
  expiresAt: isoTimestamp,
  expectedStateVersion: stateVersion.nullable(),
  approvalId: z.uuid().nullable(),
  dryRun: z.literal(true),
};

const discoverRuntimeCommandSchema = z.object({
  ...commandEnvelopeShape,
  commandType: z.literal("DISCOVER_RUNTIME_STATE"),
  payload: z.object({
    include: z.array(z.enum(["accounts", "strategies"])).min(1).max(2).refine(
      (values) => values.every((value, index) => index === 0 || values[index - 1] < value),
      "Discovery scopes must be unique and sorted",
    ),
    forceFullSnapshot: z.literal(true),
    reasonCode: z.literal("STAFF_RUNTIME_REFRESH"),
  }).strict(),
}).strict();

const collectAccountCommandSchema = z.object({
  ...commandEnvelopeShape,
  commandType: z.literal("COLLECT_ACCOUNT_SNAPSHOT"),
  payload: z.object({
    accountRefs: canonicalAccountRefs,
  }).strict(),
}).strict();

const collectExecutionsCommandSchema = z.object({
  ...commandEnvelopeShape,
  commandType: z.literal("COLLECT_EXECUTIONS"),
  payload: z.object({
    accountRefs: canonicalAccountRefs,
    fromInclusive: isoTimestamp,
    toExclusive: isoTimestamp,
  }).strict(),
}).strict();

export const readOnlyCommandEnvelopeSchema = z.discriminatedUnion("commandType", [
  discoverRuntimeCommandSchema,
  collectAccountCommandSchema,
  collectExecutionsCommandSchema,
]).superRefine((value, context) => {
  const issuedAt = Date.parse(value.issuedAt);
  const expiresAt = Date.parse(value.expiresAt);
  if (expiresAt <= issuedAt) {
    context.addIssue({ code: "custom", message: "Command expiry must be after issue time", path: ["expiresAt"] });
  }
  if (expiresAt - issuedAt > MAX_COMMAND_TTL_MS) {
    context.addIssue({ code: "custom", message: "Command lifetime exceeds the ten-minute safety limit", path: ["expiresAt"] });
  }
  if (
    value.commandType === "COLLECT_EXECUTIONS"
    && Date.parse(value.payload.toExclusive) <= Date.parse(value.payload.fromInclusive)
  ) {
    context.addIssue({
      code: "custom",
      message: "Execution range end must be after its start",
      path: ["payload", "toExclusive"],
    });
  }
});

export const acknowledgementStatusSchema = z.enum([
  "accepted",
  "rejected",
  "started",
  "progress",
  "completed",
  "failed",
  "partial",
  "expired",
  "indeterminate",
]);

const acknowledgementEvidenceSchema = z.object({
  resultEventIds: z.array(z.uuid()).max(20),
  completedScopes: z.array(z.enum(["accounts", "strategies", "executions"])).max(3),
  failedScopes: z.array(z.enum(["accounts", "strategies", "executions"])).max(3),
  retrySafe: z.boolean(),
  errorCode: z.enum([
    "NONE",
    "ADDON_OFFLINE",
    "COMMAND_TIMEOUT",
    "STATE_CHANGED",
    "UNSUPPORTED_CAPABILITY",
    "LOCAL_PERSISTENCE_FAILURE",
    "INTERNAL_ERROR",
  ]),
  observedStateVersion: stateVersion.nullable(),
  counts: z.object({
    accounts: z.number().int().min(0).max(500),
    strategies: z.number().int().min(0).max(10_000),
    executions: z.number().int().min(0).max(1_000_000),
  }).strict(),
}).strict();

const acknowledgementMessageCodeSchema = z.enum([
  "COMMAND_PERSISTED",
  "COMMAND_REJECTED_POLICY",
  "COMMAND_STARTED",
  "COMMAND_PROGRESS",
  "COMMAND_COMPLETED",
  "COMMAND_FAILED",
  "COMMAND_PARTIAL",
  "COMMAND_EXPIRED",
  "COMMAND_INDETERMINATE",
]);

const messageCodeByStatus: Record<
  z.infer<typeof acknowledgementStatusSchema>,
  z.infer<typeof acknowledgementMessageCodeSchema>
> = {
  accepted: "COMMAND_PERSISTED",
  rejected: "COMMAND_REJECTED_POLICY",
  started: "COMMAND_STARTED",
  progress: "COMMAND_PROGRESS",
  completed: "COMMAND_COMPLETED",
  failed: "COMMAND_FAILED",
  partial: "COMMAND_PARTIAL",
  expired: "COMMAND_EXPIRED",
  indeterminate: "COMMAND_INDETERMINATE",
};

export const commandAcknowledgementSchema = z.object({
  protocolVersion: z.literal(RUNTIME_PROTOCOL_VERSION),
  acknowledgementId: z.uuid(),
  commandId: z.uuid(),
  correlationId: z.uuid(),
  agentId: z.uuid(),
  leaseId: z.uuid(),
  sequence: safeSequence,
  status: acknowledgementStatusSchema,
  messageCode: acknowledgementMessageCodeSchema,
  evidence: acknowledgementEvidenceSchema,
  evidenceHash: sha256,
  occurredAt: isoTimestamp,
}).strict().superRefine((value, context) => {
  if (value.messageCode !== messageCodeByStatus[value.status]) {
    context.addIssue({
      code: "custom",
      message: "Acknowledgement message code does not match its status",
      path: ["messageCode"],
    });
  }
});

const deliveryIntegritySchema = z.object({
  canonicalization: z.literal(RUNTIME_CANONICALIZATION),
  payloadHash: sha256,
  semanticHash: sha256,
  envelopeHash: sha256,
}).strict();

export const deliveredReadOnlyCommandEnvelopeSchema = z.object({
  command: readOnlyCommandEnvelopeSchema,
  integrity: deliveryIntegritySchema,
}).strict().superRefine((value, context) => {
  const payloadHash = hashCanonicalPayload(value.command.payload);
  const semanticHash = commandSemanticHash(value.command);
  const envelopeHash = commandDeliveryEnvelopeHash(value.command, payloadHash, semanticHash);
  if (value.integrity.payloadHash !== payloadHash) {
    context.addIssue({
      code: "custom",
      message: "Delivered command payload hash mismatch",
      path: ["integrity", "payloadHash"],
    });
  }
  if (value.integrity.semanticHash !== semanticHash) {
    context.addIssue({
      code: "custom",
      message: "Delivered command semantic hash mismatch",
      path: ["integrity", "semanticHash"],
    });
  }
  if (value.integrity.envelopeHash !== envelopeHash) {
    context.addIssue({
      code: "custom",
      message: "Delivered command envelope hash mismatch",
      path: ["integrity", "envelopeHash"],
    });
  }
});

export type AgentEvent = z.infer<typeof agentEventSchema>;
export type RuntimeSnapshotEvent = z.infer<typeof runtimeSnapshotEventSchema>;
export type RuntimeObservationV2Event = z.infer<typeof runtimeObservationV2EventSchema>;
export type ProcessObservation = z.infer<typeof processObservationSchema>;
export type ReadOnlyCommandEnvelope = z.infer<typeof readOnlyCommandEnvelopeSchema>;
export type CommandAcknowledgement = z.infer<typeof commandAcknowledgementSchema>;
export type AcknowledgementStatus = z.infer<typeof acknowledgementStatusSchema>;
export type DeliveredReadOnlyCommandEnvelope = z.infer<typeof deliveredReadOnlyCommandEnvelopeSchema>;

export function runtimeStateVersion(value: { accounts: unknown; strategies: unknown }): string {
  return hashCanonicalPayload({ accounts: value.accounts, strategies: value.strategies });
}

export function eventEnvelopeHash(event: Omit<AgentEvent, "envelopeHash">): string {
  return hashCanonicalPayload(event);
}

export function commandSemanticHash(command: ReadOnlyCommandEnvelope): string {
  return hashCanonicalPayload({
    protocolVersion: command.protocolVersion,
    agentId: command.agentId,
    commandType: command.commandType,
    expectedStateVersion: command.expectedStateVersion,
    approvalId: command.approvalId,
    dryRun: command.dryRun,
    payload: command.payload,
  });
}

export function commandDeliveryEnvelopeHash(
  command: ReadOnlyCommandEnvelope,
  payloadHash = hashCanonicalPayload(command.payload),
  semanticHash = commandSemanticHash(command),
): string {
  return hashCanonicalPayload({
    command,
    integrity: {
      canonicalization: RUNTIME_CANONICALIZATION,
      payloadHash,
      semanticHash,
    },
  });
}

export function createDeliveredReadOnlyCommandEnvelope(
  input: ReadOnlyCommandEnvelope,
): DeliveredReadOnlyCommandEnvelope {
  const command = readOnlyCommandEnvelopeSchema.parse(input);
  const payloadHash = hashCanonicalPayload(command.payload);
  const semanticHash = commandSemanticHash(command);
  return deliveredReadOnlyCommandEnvelopeSchema.parse({
    command,
    integrity: {
      canonicalization: RUNTIME_CANONICALIZATION,
      payloadHash,
      semanticHash,
      envelopeHash: commandDeliveryEnvelopeHash(command, payloadHash, semanticHash),
    },
  });
}

export function acknowledgementHash(acknowledgement: CommandAcknowledgement): string {
  return hashCanonicalPayload(acknowledgement);
}

export function parseAgentEvent(input: unknown): AgentEvent {
  const event = agentEventSchema.parse(input);
  if (hashCanonicalPayload(event.payload) !== event.payloadHash) {
    throw new Error("Agent event payload hash does not match its contents");
  }
  const { envelopeHash, ...unsignedEnvelope } = event;
  if (eventEnvelopeHash(unsignedEnvelope) !== envelopeHash) {
    throw new Error("Agent event envelope hash does not match its contents");
  }
  return event;
}

export function parseRuntimeSnapshotEvent(input: unknown): RuntimeSnapshotEvent {
  const event = parseAgentEvent(input);
  if (event.eventType !== "runtime.snapshot") throw new Error("Expected a runtime snapshot event");
  return event;
}

export function parseRuntimeObservationV2Event(input: unknown): RuntimeObservationV2Event {
  const event = parseAgentEvent(input);
  if (event.eventType !== RUNTIME_OBSERVATION_V2_EVENT_TYPE) {
    throw new Error("Expected a runtime observation v2 event");
  }
  return event;
}

export function parseCommandAcknowledgement(input: unknown): CommandAcknowledgement {
  const acknowledgement = commandAcknowledgementSchema.parse(input);
  if (hashCanonicalPayload(acknowledgement.evidence) !== acknowledgement.evidenceHash) {
    throw new Error("Command acknowledgement evidence hash does not match its contents");
  }
  return acknowledgement;
}

export function parseDeliveredReadOnlyCommandEnvelope(input: unknown): DeliveredReadOnlyCommandEnvelope {
  return deliveredReadOnlyCommandEnvelopeSchema.parse(input);
}

const terminalStatuses = new Set<AcknowledgementStatus>([
  "rejected",
  "completed",
  "failed",
  "partial",
  "expired",
  "indeterminate",
]);

export function isTerminalAcknowledgement(status: AcknowledgementStatus): boolean {
  return terminalStatuses.has(status);
}

export function isAcknowledgementTransitionAllowed(
  currentStatus: string,
  nextStatus: AcknowledgementStatus,
): boolean {
  if (currentStatus === "queued") return ["accepted", "rejected", "expired"].includes(nextStatus);
  if (currentStatus === "accepted") {
    return ["started", "progress", "completed", "failed", "partial", "expired", "indeterminate"].includes(nextStatus);
  }
  if (currentStatus === "started" || currentStatus === "progress") {
    return ["progress", "completed", "failed", "partial", "expired", "indeterminate"].includes(nextStatus);
  }
  return false;
}
