import { z } from "zod";

import { hashCanonicalPayload } from "./canonical-json";

export const RUNTIME_OBSERVATION_V2_PROTOCOL = "runtime-observation/2.0" as const;

const isoTimestampSchema = z.iso.datetime({ offset: true });
const isoDateSchema = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
const softwareVersionSchema = z.string().regex(/^[A-Za-z0-9][A-Za-z0-9._+-]{0,39}$/);
const sha256Schema = z.string().regex(/^sha256:[a-f0-9]{64}$/);
const boundedCountSchema = z.number().int().min(0).max(1_000_000);
const quantitySchema = z.number().int().positive().max(1_000_000);
const priceSchema = z.number().finite().nonnegative().max(100_000_000);
const moneyMinorSchema = z.number().int().safe().min(-100_000_000_000).max(100_000_000_000);

function opaqueRef(prefix: string) {
  return z.string().regex(
    new RegExp(`^${prefix}_[a-z0-9]{16,64}$`),
    `Use the opaque ${prefix} reference generated by the local runtime`,
  );
}

const installationRefSchema = opaqueRef("install");
const sessionRefSchema = opaqueRef("session");
const processRefSchema = opaqueRef("process");
const addonRefSchema = opaqueRef("addon");
const connectionRefSchema = opaqueRef("conn");
const accountRefSchema = opaqueRef("acct");
const strategyRefSchema = opaqueRef("strat");
const positionRefSchema = opaqueRef("pos");
const orderRefSchema = opaqueRef("ord");
const executionRefSchema = opaqueRef("exec");

const sensitiveTerm = /(?:account_?(?:id|number)|api.?key|bearer|credential|password|secret|token)/i;
const maskedIdentifierSchema = z.string().regex(/^\*{4,16}[A-Za-z0-9]{2,8}$/, 'Only an ASCII mask plus the final account characters may leave the local runtime');
const identifierFingerprintSchema = z.string().regex(/^hmac-sha256:[a-f0-9]{64}$/, 'Expected a keyed account fingerprint');
const safeCodeSchema = z.string()
  .regex(/^[A-Z][A-Z0-9_.-]{0,79}$/)
  .refine((value) => !sensitiveTerm.test(value), "Sensitive names and values are forbidden");

export const runtimeStrategyTypeV2Schema = z.string().regex(/^[A-Za-z][A-Za-z0-9_.-]{0,79}$/);

const instrumentCodeSchema = z.string().regex(/^[A-Z0-9][A-Z0-9 .:/_-]{0,39}$/);
const currencySchema = z.literal("USD");

export const runtimeEnvironmentClassificationV2Schema = z.discriminatedUnion("environment", [
  z.object({
    environment: z.literal("simulation"),
    authority: z.literal("authoritative"),
    source: z.literal("ninjatrader_simulation_account"),
  }).strict(),
  z.object({
    environment: z.literal("live"),
    authority: z.literal("authoritative"),
    source: z.literal("ninjatrader_live_account"),
  }).strict(),
  z.object({
    environment: z.literal("unknown"),
    authority: z.literal("unavailable"),
    source: z.null(),
    reasonCode: z.enum([
      "ADDON_OFFLINE",
      "CLASSIFICATION_UNSUPPORTED",
      "CLASSIFICATION_CONFLICT",
      "CLASSIFICATION_UNAVAILABLE",
    ]),
  }).strict(),
]);

export const runtimeProcessHealthV2Schema = z.object({
  processRef: processRefSchema.nullable(),
  status: z.enum(["running", "starting", "stopping", "not_running", "unknown"]),
  health: z.enum(["healthy", "degraded", "offline", "unknown"]),
  version: softwareVersionSchema.nullable(),
  startedAt: isoTimestampSchema.nullable(),
  // Optional only for backward-compatible parsing of already persisted v2 events.
  observedAt: isoTimestampSchema.optional(),
}).strict().superRefine((value, context) => {
  if (value.status === "running") {
    if (value.processRef === null) context.addIssue({ code: "custom", message: "A running process requires an opaque process reference", path: ["processRef"] });
    if (value.startedAt === null) context.addIssue({ code: "custom", message: "A running process requires a start time", path: ["startedAt"] });
  }
  if (value.status === "not_running" && (value.processRef !== null || value.startedAt !== null)) {
    context.addIssue({ code: "custom", message: "A stopped process cannot retain runtime identity" });
  }
  if (value.status === "not_running" && value.health !== "offline") {
    context.addIssue({ code: "custom", message: "A stopped process must report offline health", path: ["health"] });
  }
});

export const runtimeAddonHealthV2Schema = z.object({
  addonRef: addonRefSchema.nullable(),
  status: z.enum(["connected", "initializing", "disconnected", "degraded", "unknown"]),
  health: z.enum(["healthy", "degraded", "offline", "unknown"]),
  version: softwareVersionSchema.nullable(),
  ipcAuthenticated: z.boolean(),
  capabilities: z.array(safeCodeSchema).max(100),
}).strict().superRefine((value, context) => {
  if (!value.capabilities.every((capability, index) => index === 0 || value.capabilities[index - 1] < capability)) {
    context.addIssue({ code: "custom", message: "Capabilities must be unique and sorted", path: ["capabilities"] });
  }
  if (value.status === "connected" && (value.addonRef === null || value.version === null || !value.ipcAuthenticated)) {
    context.addIssue({ code: "custom", message: "A connected Add-On requires identity, version, and authenticated IPC" });
  }
  if (value.status === "disconnected" && (value.ipcAuthenticated || value.health !== "offline")) {
    context.addIssue({ code: "custom", message: "A disconnected Add-On must be unauthenticated and offline" });
  }
});

export const runtimeConnectionObservationV2Schema = z.object({
  connectionRef: connectionRefSchema,
  displayLabel: z.string().regex(/^Connection [1-9][0-9]{0,3}$/),
  kind: z.enum(["simulation", "brokerage", "market_data", "playback", "unknown"]),
  providerCode: safeCodeSchema.nullable(),
  status: z.enum(["connected", "connecting", "disconnecting", "disconnected", "error", "unknown"]),
  health: z.enum(["healthy", "degraded", "offline", "unknown"]),
  marketDataStatus: z.enum(["live", "delayed", "stale", "unavailable", "not_applicable", "unknown"]),
  lastStateChangeAt: isoTimestampSchema.nullable(),
}).strict().superRefine((value, context) => {
  if (value.status === "connected" && value.health === "offline") {
    context.addIssue({ code: "custom", message: "A connected connection cannot report offline health", path: ["health"] });
  }
  if (value.status === "disconnected" && value.health === "healthy") {
    context.addIssue({ code: "custom", message: "A disconnected connection cannot report healthy", path: ["health"] });
  }
});

export const runtimeAccountObservationV2Schema = z.object({
  accountRef: accountRefSchema,
  maskedIdentifier: maskedIdentifierSchema,
  identifierFingerprint: identifierFingerprintSchema,
  displayLabel: z.string().regex(/^(?:Simulation|Live|Unknown) account [1-9][0-9]{0,3}$/),
  classification: runtimeEnvironmentClassificationV2Schema,
  connectionRefs: z.array(connectionRefSchema).max(20),
  status: z.enum(["connected", "disconnected", "unavailable", "unknown"]),
}).strict().superRefine((value, context) => {
  if (!value.connectionRefs.every((ref, index) => index === 0 || value.connectionRefs[index - 1] < ref)) {
    context.addIssue({ code: "custom", message: "Connection references must be unique and sorted", path: ["connectionRefs"] });
  }
  const expectedLabel = value.classification.environment === "simulation"
    ? "Simulation account "
    : value.classification.environment === "live" ? "Live account " : "Unknown account ";
  if (!value.displayLabel.startsWith(expectedLabel)) {
    context.addIssue({ code: "custom", message: "Account label must agree with its environment classification", path: ["displayLabel"] });
  }
});

const parameterValueSchema = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("boolean"), value: z.boolean() }).strict(),
  z.object({ kind: z.literal("integer"), value: z.number().int().safe().min(-1_000_000_000).max(1_000_000_000) }).strict(),
  z.object({ kind: z.literal("number"), value: z.number().finite().min(-1_000_000_000).max(1_000_000_000) }).strict(),
  z.object({ kind: z.literal("code"), value: safeCodeSchema }).strict(),
]);

const operationalParameterSchema = z.object({
  parameterCode: safeCodeSchema,
  value: parameterValueSchema,
}).strict();

export const runtimeStrategyObservationV2Schema = z.object({
  strategyRef: strategyRefSchema,
  accountRef: accountRefSchema,
  displayLabel: z.string().regex(/^Strategy [1-9][0-9]{0,4}$/),
  strategyTypeCode: runtimeStrategyTypeV2Schema,
  instrumentCode: instrumentCodeSchema,
  enabled: z.boolean(),
  runtimeState: z.enum(["disabled", "enabling", "waiting_sync", "running", "disabling", "error", "unknown"]),
  synchronizationState: z.enum(["synchronized", "not_synchronized", "pending", "not_applicable", "unknown"]),
  operationalParameters: z.array(operationalParameterSchema).max(200),
  lastStateChangeAt: isoTimestampSchema.nullable(),
}).strict().superRefine((value, context) => {
  if (!value.operationalParameters.every((parameter, index) => index === 0 || value.operationalParameters[index - 1].parameterCode < parameter.parameterCode)) {
    context.addIssue({ code: "custom", message: "Operational parameters must be unique and sorted", path: ["operationalParameters"] });
  }
  if (value.runtimeState === "running" && (!value.enabled || value.synchronizationState !== "synchronized")) {
    context.addIssue({ code: "custom", message: "Running requires enabled=true and synchronized state" });
  }
  if (!value.enabled && !["disabled", "disabling", "error", "unknown"].includes(value.runtimeState)) {
    context.addIssue({ code: "custom", message: "A disabled strategy cannot report an active runtime state", path: ["runtimeState"] });
  }
});

export const runtimePositionObservationV2Schema = z.object({
  positionRef: positionRefSchema,
  accountRef: accountRefSchema,
  strategyRef: strategyRefSchema.nullable(),
  instrumentCode: instrumentCodeSchema,
  side: z.enum(["long", "short"]),
  quantity: quantitySchema,
  averagePrice: priceSchema,
  markPrice: priceSchema.nullable(),
}).strict();

const workingOrderStateSchema = z.enum(["submitted", "accepted", "working", "change_pending", "cancel_pending", "unknown"]);
const completedOrderStateSchema = z.enum(["filled", "cancelled", "rejected", "expired"]);

export const runtimeOrderObservationV2Schema = z.discriminatedUnion("lifecycle", [
  z.object({
    orderRef: orderRefSchema,
    accountRef: accountRefSchema,
    strategyRef: strategyRefSchema.nullable(),
    instrumentCode: instrumentCodeSchema,
    lifecycle: z.literal("working"),
    state: workingOrderStateSchema,
    side: z.enum(["buy", "sell"]),
    orderType: z.enum(["market", "limit", "stop_market", "stop_limit", "unknown"]),
    quantity: quantitySchema,
    filledQuantity: boundedCountSchema,
    limitPrice: priceSchema.nullable(),
    stopPrice: priceSchema.nullable(),
    submittedAt: isoTimestampSchema,
    completedAt: z.null(),
  }).strict(),
  z.object({
    orderRef: orderRefSchema,
    accountRef: accountRefSchema,
    strategyRef: strategyRefSchema.nullable(),
    instrumentCode: instrumentCodeSchema,
    lifecycle: z.literal("completed"),
    state: completedOrderStateSchema,
    side: z.enum(["buy", "sell"]),
    orderType: z.enum(["market", "limit", "stop_market", "stop_limit", "unknown"]),
    quantity: quantitySchema,
    filledQuantity: boundedCountSchema,
    limitPrice: priceSchema.nullable(),
    stopPrice: priceSchema.nullable(),
    submittedAt: isoTimestampSchema,
    completedAt: isoTimestampSchema,
  }).strict(),
]).superRefine((value, context) => {
  if (value.filledQuantity > value.quantity) {
    context.addIssue({ code: "custom", message: "Filled quantity cannot exceed order quantity", path: ["filledQuantity"] });
  }
  if (value.lifecycle === "completed" && Date.parse(value.completedAt) < Date.parse(value.submittedAt)) {
    context.addIssue({ code: "custom", message: "Order completion cannot precede submission", path: ["completedAt"] });
  }
  if (value.state === "filled" && value.filledQuantity !== value.quantity) {
    context.addIssue({ code: "custom", message: "A filled order must have its full quantity filled", path: ["filledQuantity"] });
  }
});

export const runtimeExecutionObservationV2Schema = z.object({
  executionRef: executionRefSchema,
  orderRef: orderRefSchema,
  accountRef: accountRefSchema,
  strategyRef: strategyRefSchema.nullable(),
  instrumentCode: instrumentCodeSchema,
  side: z.enum(["buy", "sell"]),
  quantity: quantitySchema,
  price: priceSchema,
  commissionMinor: moneyMinorSchema.nullable(),
  executedAt: isoTimestampSchema,
}).strict();

const pnlSourceSchema = z.enum([
  "ninjatrader_account_item",
  "ninjatrader_performance",
  "calculated_by_companion",
  "manager_ledger",
]);

const availableMoneySchema = z.object({
  availability: z.literal("available"),
  currency: currencySchema,
  amountMinor: moneyMinorSchema,
  source: pnlSourceSchema,
}).strict();

const unavailableMoneySchema = z.object({
  availability: z.literal("unavailable"),
  currency: currencySchema,
  amountMinor: z.null(),
  source: z.null(),
  reasonCode: z.enum([
    "ADDON_OFFLINE",
    "ACCOUNT_DISCONNECTED",
    "SOURCE_UNSUPPORTED",
    "SOURCE_ERROR",
    "NOT_OBSERVED_YET",
  ]),
}).strict();

export const runtimeMoneyObservationV2Schema = z.discriminatedUnion("availability", [
  availableMoneySchema,
  unavailableMoneySchema,
]);

export const runtimePnlObservationV2Schema = z.object({
  accountRef: accountRefSchema,
  sessionDate: isoDateSchema,
  daily: z.object({
    realized: runtimeMoneyObservationV2Schema,
    unrealized: runtimeMoneyObservationV2Schema,
    total: runtimeMoneyObservationV2Schema,
  }).strict(),
  nativeLifetime: runtimeMoneyObservationV2Schema,
  managerObservedCumulative: z.object({
    value: runtimeMoneyObservationV2Schema,
    observedSince: isoTimestampSchema.nullable(),
  }).strict(),
}).strict().superRefine((value, context) => {
  const { realized, unrealized, total } = value.daily;
  const componentsAvailable = realized.availability === "available" && unrealized.availability === "available";
  if (componentsAvailable) {
    if (total.availability !== "available") {
      context.addIssue({ code: "custom", message: "Daily total must be available when both components are available", path: ["daily", "total"] });
    } else if (total.amountMinor !== realized.amountMinor + unrealized.amountMinor) {
      context.addIssue({ code: "custom", message: "Daily total must equal realized plus unrealized P&L", path: ["daily", "total", "amountMinor"] });
    }
  } else if (total.availability !== "unavailable") {
    context.addIssue({ code: "custom", message: "Daily total must be unavailable when a component is unavailable", path: ["daily", "total"] });
  }
  if (realized.availability === "available" && !["ninjatrader_account_item", "ninjatrader_performance"].includes(realized.source)) {
    context.addIssue({ code: "custom", message: "Daily realized P&L requires a NinjaTrader source", path: ["daily", "realized", "source"] });
  }
  if (unrealized.availability === "available" && unrealized.source !== "ninjatrader_account_item") {
    context.addIssue({ code: "custom", message: "Daily unrealized P&L requires the NinjaTrader account item source", path: ["daily", "unrealized", "source"] });
  }
  if (total.availability === "available" && total.source !== "calculated_by_companion") {
    context.addIssue({ code: "custom", message: "Daily total must be calculated by the companion", path: ["daily", "total", "source"] });
  }
  if (value.nativeLifetime.availability === "available" && value.nativeLifetime.source !== "ninjatrader_performance") {
    context.addIssue({ code: "custom", message: "Native lifetime P&L requires the NinjaTrader performance source", path: ["nativeLifetime", "source"] });
  }
  const manager = value.managerObservedCumulative;
  if (manager.value.availability === "available") {
    if (manager.value.source !== "manager_ledger" || manager.observedSince === null) {
      context.addIssue({ code: "custom", message: "Manager cumulative P&L requires its ledger source and observation start" });
    }
  } else if (manager.observedSince !== null) {
    context.addIssue({ code: "custom", message: "Unavailable manager cumulative P&L cannot claim an observation start", path: ["managerObservedCumulative", "observedSince"] });
  }
});

export const runtimeCollectionErrorV2Schema = z.object({
  code: z.enum([
    "ADDON_OFFLINE",
    "CAPABILITY_UNSUPPORTED",
    "COLLECTION_TIMEOUT",
    "CONNECTION_UNAVAILABLE",
    "INCONSISTENT_RUNTIME_STATE",
    "SOURCE_ERROR",
  ]),
  retryable: z.boolean(),
}).strict();

export const runtimeCollectionScopeV2Schema = z.object({
  status: z.enum(["complete", "partial", "unavailable"]),
  itemCount: boundedCountSchema,
  errors: z.array(runtimeCollectionErrorV2Schema).max(20),
}).strict().superRefine((value, context) => {
  if (value.status === "complete" && value.errors.length !== 0) {
    context.addIssue({ code: "custom", message: "A complete collection cannot contain errors", path: ["errors"] });
  }
  if (value.status !== "complete" && value.errors.length === 0) {
    context.addIssue({ code: "custom", message: "An incomplete collection requires a typed error", path: ["errors"] });
  }
  if (value.status === "unavailable" && value.itemCount !== 0) {
    context.addIssue({ code: "custom", message: "An unavailable collection cannot contain observations", path: ["itemCount"] });
  }
  const keys = new Set(value.errors.map((error) => error.code));
  if (keys.size !== value.errors.length) {
    context.addIssue({ code: "custom", message: "Collection error codes must be unique", path: ["errors"] });
  }
});

const scopeKeys = [
  "process",
  "addon",
  "connections",
  "accounts",
  "strategies",
  "positions",
  "orders",
  "executions",
  "pnl",
] as const;

const collectionCompletenessSchema = z.object({
  overall: z.enum(["complete", "partial", "unavailable"]),
  scopes: z.object({
    process: runtimeCollectionScopeV2Schema,
    addon: runtimeCollectionScopeV2Schema,
    connections: runtimeCollectionScopeV2Schema,
    accounts: runtimeCollectionScopeV2Schema,
    strategies: runtimeCollectionScopeV2Schema,
    positions: runtimeCollectionScopeV2Schema,
    orders: runtimeCollectionScopeV2Schema,
    executions: runtimeCollectionScopeV2Schema,
    pnl: runtimeCollectionScopeV2Schema,
  }).strict(),
}).strict();

export const runtimeObservationV2StateSchema = z.object({
  process: runtimeProcessHealthV2Schema.nullable(),
  addon: runtimeAddonHealthV2Schema.nullable(),
  connections: z.array(runtimeConnectionObservationV2Schema).max(100),
  accounts: z.array(runtimeAccountObservationV2Schema).max(500),
  strategies: z.array(runtimeStrategyObservationV2Schema).max(10_000),
  positions: z.array(runtimePositionObservationV2Schema).max(10_000),
  orders: z.array(runtimeOrderObservationV2Schema).max(10_000),
  executions: z.array(runtimeExecutionObservationV2Schema).max(10_000),
  pnl: z.array(runtimePnlObservationV2Schema).max(500),
  collection: collectionCompletenessSchema,
}).strict().superRefine((value, context) => {
  const arrays = {
    connections: value.connections,
    accounts: value.accounts,
    strategies: value.strategies,
    positions: value.positions,
    orders: value.orders,
    executions: value.executions,
    pnl: value.pnl,
  } as const;
  const refs = {
    connections: value.connections.map((entry) => entry.connectionRef),
    accounts: value.accounts.map((entry) => entry.accountRef),
    strategies: value.strategies.map((entry) => entry.strategyRef),
    positions: value.positions.map((entry) => entry.positionRef),
    orders: value.orders.map((entry) => entry.orderRef),
    executions: value.executions.map((entry) => entry.executionRef),
    pnl: value.pnl.map((entry) => entry.accountRef),
  } as const;
  for (const [scope, scopeRefs] of Object.entries(refs)) {
    if (!scopeRefs.every((ref, index) => index === 0 || scopeRefs[index - 1] < ref)) {
      context.addIssue({ code: "custom", message: `${scope} references must be unique and sorted`, path: [scope] });
    }
  }

  const expectedCounts: Record<(typeof scopeKeys)[number], number> = {
    process: value.process === null ? 0 : 1,
    addon: value.addon === null ? 0 : 1,
    connections: arrays.connections.length,
    accounts: arrays.accounts.length,
    strategies: arrays.strategies.length,
    positions: arrays.positions.length,
    orders: arrays.orders.length,
    executions: arrays.executions.length,
    pnl: arrays.pnl.length,
  };
  for (const scope of scopeKeys) {
    if (value.collection.scopes[scope].itemCount !== expectedCounts[scope]) {
      context.addIssue({ code: "custom", message: "Collection count does not match observations", path: ["collection", "scopes", scope, "itemCount"] });
    }
  }
  const statuses = scopeKeys.map((scope) => value.collection.scopes[scope].status);
  const expectedOverall = statuses.every((status) => status === "complete")
    ? "complete"
    : statuses.every((status) => status === "unavailable") ? "unavailable" : "partial";
  if (value.collection.overall !== expectedOverall) {
    context.addIssue({ code: "custom", message: "Overall completeness does not match collection scopes", path: ["collection", "overall"] });
  }

  const accountRefs = new Set(value.accounts.map((entry) => entry.accountRef));
  const accountFingerprints = new Set(value.accounts.map((entry) => entry.identifierFingerprint));
  const connectionRefs = new Set(value.connections.map((entry) => entry.connectionRef));
  const strategyRefs = new Set(value.strategies.map((entry) => entry.strategyRef));
  const orderRefs = new Set(value.orders.map((entry) => entry.orderRef));
  if (accountFingerprints.size !== value.accounts.length) {
    context.addIssue({ code: 'custom', message: 'Snapshot contains duplicate account fingerprints', path: ['accounts'] });
  }
  value.accounts.forEach((account, index) => account.connectionRefs.forEach((ref) => {
    if (!connectionRefs.has(ref)) context.addIssue({ code: "custom", message: "Account references an absent connection", path: ["accounts", index, "connectionRefs"] });
  }));
  value.strategies.forEach((strategy, index) => {
    if (!accountRefs.has(strategy.accountRef)) context.addIssue({ code: "custom", message: "Strategy references an absent account", path: ["strategies", index, "accountRef"] });
  });
  value.positions.forEach((position, index) => {
    if (!accountRefs.has(position.accountRef)) context.addIssue({ code: "custom", message: "Position references an absent account", path: ["positions", index, "accountRef"] });
    if (position.strategyRef !== null && !strategyRefs.has(position.strategyRef)) context.addIssue({ code: "custom", message: "Position references an absent strategy", path: ["positions", index, "strategyRef"] });
  });
  value.orders.forEach((order, index) => {
    if (!accountRefs.has(order.accountRef)) context.addIssue({ code: "custom", message: "Order references an absent account", path: ["orders", index, "accountRef"] });
    if (order.strategyRef !== null && !strategyRefs.has(order.strategyRef)) context.addIssue({ code: "custom", message: "Order references an absent strategy", path: ["orders", index, "strategyRef"] });
  });
  value.executions.forEach((execution, index) => {
    if (!accountRefs.has(execution.accountRef)) context.addIssue({ code: "custom", message: "Execution references an absent account", path: ["executions", index, "accountRef"] });
    if (!orderRefs.has(execution.orderRef)) context.addIssue({ code: "custom", message: "Execution references an absent order", path: ["executions", index, "orderRef"] });
    if (execution.strategyRef !== null && !strategyRefs.has(execution.strategyRef)) context.addIssue({ code: "custom", message: "Execution references an absent strategy", path: ["executions", index, "strategyRef"] });
  });
  value.pnl.forEach((pnl, index) => {
    if (!accountRefs.has(pnl.accountRef)) context.addIssue({ code: "custom", message: "P&L references an absent account", path: ["pnl", index, "accountRef"] });
  });
  if (value.collection.scopes.accounts.status === "complete" && value.collection.scopes.pnl.status === "complete") {
    if (value.pnl.length !== value.accounts.length || value.accounts.some((account) => !value.pnl.some((pnl) => pnl.accountRef === account.accountRef))) {
      context.addIssue({ code: "custom", message: "Complete P&L collection requires one observation per account", path: ["pnl"] });
    }
  }
});

export const runtimeObservationV2Schema = z.object({
  protocolVersion: z.literal(RUNTIME_OBSERVATION_V2_PROTOCOL),
  observationId: z.uuid(),
  source: z.object({
    collector: z.literal("vps_companion_agent"),
    authority: z.literal("ninjatrader_runtime"),
    installationRef: installationRefSchema,
    collectionSessionRef: sessionRefSchema,
  }).strict(),
  asOf: isoTimestampSchema,
  freshness: z.object({
    status: z.enum(["fresh", "stale", "unknown"]),
    ageMs: z.number().int().min(0).max(86_400_000).nullable(),
    maxAgeMs: z.number().int().positive().max(3_600_000),
  }).strict(),
  stateDigest: sha256Schema,
  state: runtimeObservationV2StateSchema,
}).strict().superRefine((value, context) => {
  if (value.freshness.status === "unknown" && value.freshness.ageMs !== null) {
    context.addIssue({ code: "custom", message: "Unknown freshness cannot claim a measured age", path: ["freshness", "ageMs"] });
  }
  if (value.freshness.status === "fresh" && (value.freshness.ageMs === null || value.freshness.ageMs > value.freshness.maxAgeMs)) {
    context.addIssue({ code: "custom", message: "Fresh state requires a measured age within the freshness limit", path: ["freshness"] });
  }
  if (value.freshness.status === "stale" && (value.freshness.ageMs === null || value.freshness.ageMs <= value.freshness.maxAgeMs)) {
    context.addIssue({ code: "custom", message: "Stale state requires an age beyond the freshness limit", path: ["freshness"] });
  }
  if (value.stateDigest !== hashCanonicalPayload(value.state)) {
    context.addIssue({ code: "custom", message: "State digest does not match the canonical runtime observation", path: ["stateDigest"] });
  }
});

export type RuntimeEnvironmentClassificationV2 = z.infer<typeof runtimeEnvironmentClassificationV2Schema>;
export type RuntimeProcessHealthV2 = z.infer<typeof runtimeProcessHealthV2Schema>;
export type RuntimeAddonHealthV2 = z.infer<typeof runtimeAddonHealthV2Schema>;
export type RuntimeConnectionObservationV2 = z.infer<typeof runtimeConnectionObservationV2Schema>;
export type RuntimeAccountObservationV2 = z.infer<typeof runtimeAccountObservationV2Schema>;
export type RuntimeStrategyObservationV2 = z.infer<typeof runtimeStrategyObservationV2Schema>;
export type RuntimePositionObservationV2 = z.infer<typeof runtimePositionObservationV2Schema>;
export type RuntimeOrderObservationV2 = z.infer<typeof runtimeOrderObservationV2Schema>;
export type RuntimeExecutionObservationV2 = z.infer<typeof runtimeExecutionObservationV2Schema>;
export type RuntimeMoneyObservationV2 = z.infer<typeof runtimeMoneyObservationV2Schema>;
export type RuntimePnlObservationV2 = z.infer<typeof runtimePnlObservationV2Schema>;
export type RuntimeCollectionScopeV2 = z.infer<typeof runtimeCollectionScopeV2Schema>;
export type RuntimeObservationV2State = z.infer<typeof runtimeObservationV2StateSchema>;
export type RuntimeObservationV2 = z.infer<typeof runtimeObservationV2Schema>;

export function runtimeObservationV2StateDigest(state: RuntimeObservationV2State): string {
  return hashCanonicalPayload(runtimeObservationV2StateSchema.parse(state));
}

/**
 * The current Add-On collects Runtime-v2 inventory sequentially. A scope is
 * usable for non-actuating identity and binding workflows only when its sole
 * limitation is that declared non-atomic collection mode. This deliberately
 * preserves `partial`; mutation readiness requires separate just-in-time
 * evidence.
 */
export function isSequentialInventoryScopeUsable(scope: RuntimeCollectionScopeV2): boolean {
  if (scope.status === "complete") return scope.errors.length === 0;
  return scope.status === "partial"
    && scope.errors.length === 1
    && scope.errors[0].code === "CAPABILITY_UNSUPPORTED"
    && scope.errors[0].retryable === false;
}

export function parseRuntimeObservationV2(input: unknown): RuntimeObservationV2 {
  return runtimeObservationV2Schema.parse(input);
}
